---
S1:
    hostname: S1
    groups:
        - cisco_group

S2:
    hostname: S2
    groups:
        - cisco_group

S3:
    hostname: S3
    groups:
        - cisco_group

S4:
    hostname: S4
    groups:
        - cisco_group

S5:
    hostname: S5
    groups:
        - cisco_group
